# Generated by Django 5.1.1 on 2024-09-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="s1",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s2",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s3",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s4",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s5",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s6",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s7",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s8",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="s9",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="museum_name_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="waiting_list",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
